import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FooterPage from "../components/FooterPage";
import NavbarHeader from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarHeader />
        {children}
        <FooterPage />
      </body>
    </html>
  );
}
